name: "Comfort Cloud"
description: "GitHub Actions for controlling a Panasonic Comfort Cloud enabled heatpump based on electricity price"
branding:
  icon: "thermometer"
  color: "green"
inputs:
  username:
    description: "Panasonic Comfort Cloud username"
    required: true
  password:
    description: "Panasonic Comfort Cloud password"
    required: true
  area:
    description: "Electricity area"
    required: true
    type: choice
    options: 
    - DK1
    - DK2
  network-company:
    description: "Electricity network company"
    required: true
    type: choice
    options: 
    - none
    - cerius_c
    - dinel_c
    - elektrus_c
    - elinor
    - el-net_kongerslev
    - elnet_midt_c
    - flow_elnet
    - forsyning_elnet
    - gev_elnet_c
    - hammel_elforsyning_net_as
    - n1_c
  company:
    description: "Electricity company"
    required: true
    type: choice
    options: 
    - nettopower
  price-max:
    description: "Electricity price max"
    required: true
    type: number
outputs:
  changes:
    description: "Indicates if there are changes from the latest release"
    value: ${{ steps.run.outputs.changes }}
  latest:
    description: "The lastest release on the workflow branch"
    value: ${{ steps.run.outputs.latest }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run
      run: python main.py
      env:
        COMFORT_CLOUD_USERNAME: ${{ inputs.username }}
        COMFORT_CLOUD_PASSWORD: ${{ inputs.password }}
        COMFORT_CLOUD_AREA: ${{ inputs.area }}
        COMFORT_CLOUD_NETWORK_COMPANY: ${{ inputs.network-company }}
        COMFORT_CLOUD_COMPANY: ${{ inputs.company }}
        COMFORT_CLOUD_PRICE_MAX: ${{ inputs.price-max }}
