name: "Comfort Cloud Action"
description: "GitHub Actions for controlling a Panasonic Comfort Cloud enabled heatpump based on electricity price"
branding:
  icon: "thermometer"
  color: "green"
inputs:
  username:
    description: "Panasonic Comfort Cloud username"
    required: true
  password:
    description: "Panasonic Comfort Cloud password"
    required: true
  area:
    description: "Electricity area"
    required: true
    type: choice
    options: 
    - DK1
    - DK2
  network-company:
    description: "Electricity network company"
    required: true
    type: choice
    options:
    - none
    - cerius_c
    - dinel_c
    - elektrus_c
    - elinor
    - el-net_kongerslev
    - elnet_midt_c
    - flow_elnet
    - forsyning_elnet
    - gev_elnet_c
    - hammel_elforsyning_net_as
    - hjerting_transformatorforening
    - hurup_elvrk_net_c
    - ikast_el_net_as_c
    - kimbrer_c
    - konstant_c
    - l-net
    - laesoe_elnet_c
    - midtfyns_elforsyning_c
    - n1_c
    - nakskov_elnet_e
    - netselskabet_elvaerk_331_c
    - netselskabet_elvaerk_c
    - nke-elnet
    - nord_energi_net
    - noe_net
    - radius_c
    - rah_c
    - ravdex
    - sunds_net
    - tarm_elværk_net_as
    - trefor_el-net_c
    - trefor_el-net_oest_c
    - veksel
    - videbaek_elnet_c
    - vildbjerg_elnet_c
    - vores_elnet
    - zeanet
    - aal_el_net_c
  electricity-company:
    description: "Electricity company"
    required: true
    type: choice
    options:
    - altid-energi
    - andel_energi_solenergi
    - andel_energi_timeenergi
    - andel_energi_variabel_pris
    - atompower
    - aura_flexel
    - aura_flexel_intro
    - aura_flexel_intro2
    - b_energy
    - beof_timeenergi
    - beof_timeenergi_maaned
    - budget_energi_variabel_elpris
    - clever
    - dansk_stroem_flex
    - e-go
    - edison_variabel
    - energi_fyn_groen_kostpris_plus_50ore
    - energi_fyn_kostpris_plus_50ore
    - energi_fyn_spotel
    - energi_viborg
    - energi_viborg_intro_flex_el
    - energidrift
    - energiselskabet_elg
    - energynordic_nordicflex
    - enkel_energi-pioneers
    - ewii_groen_fremtid
    - ewii_groen_indkoebspris
    - ewii_groen_timepris
    - ewii_timepris
    - ewii_timepris_intro
    - fairpris_fast
    - fairpris_flex
    - fairstrom_fair-spot-kvartal
    - fairstrom_fair-spot-maaned
    - forskel_spotel
    - forsyning_helsingoer_kronborg_el
    - forsyningen
    - gasel
    - gasel_borspris
    - gnp_flex_privat
    - gnp_variabel_garanti
    - go-energi_go_spot_energi
    - go-energi_go_spot_maaned
    - green_power_energy_variabel_privat
    - greenbow_elaftale
    - groen_nordisk
    - groen_ok_el_flex
    - groen_ok_el_flex_intro
    - groen_ok_el_spot
    - groen_ok_el_spot_intro
    - gronelforsyning_gron-fremtid
    - gronelforsyning_gronflex
    - homecharge
    - iwatt_Variabel
    - jysk_energi_fdm-stroem
    - jysk_energi_variabel_strom
    - kernfull
    - lokal_energi
    - looad
    - modstroem_g
    - modstroem_nemel
    - modstroem_premium
    - modstroem_spotel
    - nef-bil_og_bolig
    - nef-el_til_kostpris
    - nef-variabel_pris_uden_aconto
    - nettopower
    - nordiczol_groen-nordic
    - nordiczol_nordic-velkommen
    - nordisk_energy
    - norlys_flexel
    - norlys_flexel_intro
    - nrgi_time
    - nrgi_time_klima
    - oe_groen_stroem
    - oe_stroem
    - ok_el_flex
    - ok_el_spot
    - ok_el_variabelpris
    - power_fuel
    - preasy
    - raakraft
    - samstrom_ren_spar
    - samstrom_ren_spot
    - sef_energi_as_dyrenes-energi
    - sef_energi_as_fleksvind
    - sef_energi_as_timeel
    - sk-energi_flex-el
    - spotpris
    - stroemfordel_flexstroem_privat
    - stromlinet_solenergi
    - stromlinet_vindenergi
    - stromplus_49
    - stromplus_prisgaranti
    - stromplus_prisgaranti_intro
    - stromtid_klimahelt
    - struer_flex
    - vedvarende_el
    - vedvarende_fri
    - velkommen
    - verdo_variabel_timepris
    - vest_energi
    - vest_energi_gron_elaftale
    - vest_energi_spot
    - vestforsyning_plus
    - vestforsyning_spot
    - vesthimmerlands_fri_el_spot
    - vindstoed_aktive_energiforbrugere
    - vindstoed_danskvind
    - vindstoed_elforbundet_2025
    - vindstoed_spotvind
    - vindstoed_timeel
    - vindstoed_vestroem
    - zapp_energy
    - zosani-velkommen-energi 
  price-max:
    description: "Electricity price max"
    required: true
    type: number
  temperature-min:
    description: "Minimum temperature to keep"
    required: false
    default: 0
    type: number
  temperature-max:
    description: "Maximum temperature to keep"
    required: false
    default: 25
    type: number
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
    - name: Run
      shell: bash
      run: python $GITHUB_ACTION_PATH/comfort_cloud.py
      env:
        COMFORT_CLOUD_USERNAME: ${{ inputs.username }}
        COMFORT_CLOUD_PASSWORD: ${{ inputs.password }}
        COMFORT_CLOUD_AREA: ${{ inputs.area }}
        COMFORT_CLOUD_NETWORK_COMPANY: ${{ inputs.network-company }}
        COMFORT_CLOUD_ELECTRICITY_COMPANY: ${{ inputs.electricity-company }}
        COMFORT_CLOUD_PRICE_MAX: ${{ inputs.price-max }}
        COMFORT_CLOUD_TEMPERATURE_MIN: ${{ inputs.temperature-min }}
        COMFORT_CLOUD_TEMPERATURE_MAX: ${{ inputs.temperature-max }}
